// 沪教牛津版（深圳用，2024 审核新版）三、四年级四册主题题库。
// 词汇按单元整理，句型为对应知识点的原创练习；资料来源与范围见设计文档。
// 花括号标出句子中唯一的挖空词，后三项为已经人工检查的错误选项。
const unit=(title,words,sentences)=>({title,words:words.split('|').map(entry=>{const [word,meaning]=entry.split('=');return {word,meaning};}),sentences});

export const ENGLISH_BOOKS=[
  {id:'3A',grade:3,title:'三年级上册',units:[
    unit('How do we feel?',
      'happy=开心的|sad=伤心的|angry=生气的|tired=疲倦的|boy=男孩|girl=女孩|not=不|too=也',[
      ['I {am} happy.','is','are','be'],
      ['You {are} tired.','am','is','be'],
      ['How {are} you?','am','is','be'],
      ['The boy {is} sad.','am','are','be'],
    ]),
    unit("What's interesting about families?",
      'grandfather=爷爷；外公|grandmother=奶奶；外婆|father=爸爸|mother=妈妈|sister=姐妹|brother=兄弟|family=家庭|this=这个',[
      ['This {is} my family.','am','are','be'],
      ['They {are} my brothers.','am','is','be'],
      ['Who {is} she? She is my mother.','am','are','be'],
      ['My father and mother {are} happy.','am','is','be'],
    ]),
    unit('What do we look like?',
      'head=头|hair=头发|eye=眼睛|ear=耳朵|nose=鼻子|mouth=嘴|face=脸|long=长的|short=短的',[
      ['I {have} two eyes.','has','having','am'],
      ['She {has} long hair.','have','having','is'],
      ['My ears {are} small.','am','is','be'],
      ['He {has} a big nose.','have','having','are'],
    ]),
    unit('How do we have fun?',
      'skip=跳绳|run=跑|fly=放飞|kite=风筝|skateboard=滑板|ride=骑|bike=自行车|fun=乐趣',[
      ['Can you {ride} a bike?','rides','riding','to ride'],
      ['I can {run} fast.','runs','running','to run'],
      ['{Can} you skip? Yes, I can.','Does','Is','Are'],
      ['She can {fly} a kite.','flies','flying','to fly'],
    ]),
    unit('What do we eat?',
      'milk=牛奶|juice=果汁|apple=苹果|banana=香蕉|grape=葡萄|tomato=西红柿|carrot=胡萝卜|fish=鱼；鱼肉|meat=肉',[
      ['{Do} you like apples? Yes, I do.','Does','Is','Are'],
      ['He {likes} bananas.','like','liking','is'],
      ['I {like} milk.','likes','liking','am'],
      ['She does not {like} carrots.','likes','liking','to like'],
    ]),
    unit('What do we like about small animals?',
      'squirrel=松鼠|rabbit=兔子|cat=猫|mouse=老鼠|dog=狗|frog=青蛙|animal=动物|tail=尾巴',[
      ['The rabbit {has} long ears.','have','having','are'],
      ['Can a frog {jump}?','jumps','jumping','to jump'],
      ['{Does} she like cats? Yes, she does.','Do','Is','Are'],
      ['The dogs {are} small.','am','is','be'],
    ]),
    unit('What do we know about weather?',
      'sunny=晴朗的|cloudy=多云的|rainy=下雨的|windy=有风的|weather=天气|hot=热的|cold=冷的|today=今天',[
      ['It {is} sunny today.','am','are','be'],
      ['How {is} the weather?','am','are','be'],
      ['We {are} cold.','am','is','be'],
      ['{Is} it rainy? Yes, it is.','Do','Does','Are'],
    ]),
    unit('Why do we like birthdays?',
      'birthday=生日|cake=蛋糕|candle=蜡烛|gift=礼物|doll=玩偶|card=卡片|noodles=面条|plane=飞机',[
      ['How old {are} you?','am','is','be'],
      ['She {is} nine years old.','am','are','be'],
      ['{Do} you like your gift? Yes, I do.','Does','Is','Are'],
      ['Let us {make} a birthday card.','makes','making','to make'],
    ]),
  ]},
  {id:'3B',grade:3,title:'三年级下册',units:[
    unit('How do we spend our free time?',
      'read=阅读|sing=唱歌|paint=用颜料画|dance=跳舞|swim=游泳|basketball=篮球|football=足球|hobby=业余爱好|talk=谈论',[
      ['I like {reading} books.','reads','to reading','am read'],
      ['She {likes} singing.','like','liking','is like'],
      ['{Do} you like dancing? Yes, I do.','Does','Is','Are'],
      ['He can {swim}.','swims','swimming','to swim'],
    ]),
    unit('How do we make friends?',
      'game=游戏|photo=照片|boat=小船|mountain=山|story=故事|great=很棒的|join=加入|meet=遇见|friend=朋友',[
      ['Let us {play} a game.','plays','playing','to play'],
      ['Do you {like} telling stories?','likes','liking','to like'],
      ['Can I {join} you?','joins','joining','to join'],
      ['We can {row} a boat together.','rows','rowing','to row'],
    ]),
    unit('What do we wear?',
      'sweater=毛衣|skirt=女裙|dress=连衣裙|shirt=衬衫|trousers=裤子|shorts=短裤|coat=外套|cap=便帽|shoes=鞋子|wear=穿；戴',[
      ['What {do} you wear on a cold day?','does','is','are'],
      ['She {wears} a coat every day.','wear','wearing','is wear'],
      ['{Is} this your shirt? Yes, it is.','Do','Does','Are'],
      ['These shoes {are} blue.','am','is','be'],
    ]),
    unit('What sounds can we hear?',
      'hear=听见|sound=声音|bird=鸟|train=火车|bus=公共汽车|car=小汽车|loud=响亮的|quiet=安静的',[
      ['What can you {hear}?','hears','hearing','to hear'],
      ['I can {hear} a bird.','hears','hearing','to hear'],
      ['{Can} you hear the bus? Yes, I can.','Does','Is','Are'],
      ['The train {is} loud.','am','are','be'],
    ]),
    unit('Where can we see colours?',
      'red=红色的|yellow=黄色的|blue=蓝色的|green=绿色的|orange=橙色的|purple=紫色的|pink=粉色的|colour=颜色',[
      ['What colour {is} it?','am','are','be'],
      ['The flowers {are} yellow.','am','is','be'],
      ['I can {see} a rainbow.','sees','seeing','to see'],
      ['{Is} your bag green? Yes, it is.','Do','Does','Are'],
    ]),
    unit('What are our homes like?',
      'home=家|bedroom=卧室|bathroom=浴室|kitchen=厨房|room=房间|bed=床|table=桌子|chair=椅子',[
      ['There {is} a bed in my room.','am','are','be'],
      ['There {are} two chairs in the kitchen.','am','is','be'],
      ['{Is} there a table? Yes, there is.','Do','Does','Are'],
      ['My home {has} three bedrooms.','have','having','are'],
    ]),
    unit('What do we do at school?',
      'school=学校|classroom=教室|library=图书馆|playground=操场|lesson=课|teacher=老师|student=学生|book=书',[
      ['We {have} lessons in the classroom.','has','having','are'],
      ['There {are} many books in the library.','am','is','be'],
      ['{Do} you like your school? Yes, I do.','Does','Is','Are'],
      ['She {reads} books every day.','read','reading','is read'],
    ]),
    unit("What do you do on Children's Day?",
      'park=公园|cinema=电影院|museum=博物馆|zoo=动物园|party=聚会|child=儿童|children=孩子们|visit=参观',[
      ["What {do} you do on Children's Day?",'does','is','are'],
      ['Let us {go} to the park.','goes','going','to go'],
      ['We can {visit} the museum.','visits','visiting','to visit'],
      ['The children {are} happy.','am','is','be'],
    ]),
  ]},
  {id:'4A',grade:4,title:'四年级上册',units:[
    unit('Where do people live?',
      'city=城市|building=楼房|flat=公寓|street=街道|country=乡村|farm=农场|house=房子|people=人们|live=居住',[
      ['Where {do} you live?','does','is','are'],
      ['He {lives} in a city.','live','living','is live'],
      ['{Does} she live on a farm? Yes, she does.','Do','Is','Are'],
      ['They {live} in a big house.','lives','living','are live'],
    ]),
    unit('Where do animals live?',
      'eagle=老鹰|owl=猫头鹰|honeybee=蜜蜂|nest=鸟巢|hive=蜂巢|hole=洞|tree=树|forest=森林',[
      ['Where {does} the owl live?','do','is','are'],
      ['Bees {live} in a hive.','lives','living','are live'],
      ['The eagle {has} a nest.','have','having','are'],
      ['{Do} these birds live in trees? Yes, they do.','Does','Is','Are'],
    ]),
    unit('How do we use numbers?',
      'number=数字|odd=奇数的|even=偶数的|plus=加|minus=减|equal=等于|answer=答案|count=数数',[
      ['Two plus three {is} five.','am','are','be'],
      ['Can you {count} to twenty?','counts','counting','to count'],
      ['These numbers {are} even.','am','is','be'],
      ['{Is} seven an odd number? Yes, it is.','Do','Does','Are'],
    ]),
    unit('What do we buy?',
      'supermarket=超市|rice=大米|egg=鸡蛋|money=钱|buy=买|potato=土豆|bread=面包|shop=商店',[
      ['How much {is} the rice?','am','are','be'],
      ['How much {are} the eggs?','am','is','be'],
      ['{Do} you need any bread? Yes, I do.','Does','Is','Are'],
      ['She {buys} milk every day.','buy','buying','is buy'],
    ]),
    unit('How are the seasons different?',
      'spring=春天|summer=夏天|autumn=秋天|winter=冬天|warm=温暖的|hot=热的|cool=凉爽的|cold=冷的|season=季节',[
      ['It {is} warm in spring.','am','are','be'],
      ['We can {swim} in summer.','swims','swimming','to swim'],
      ['{Does} she like winter? Yes, she does.','Do','Is','Are'],
      ['The leaves {are} yellow in autumn.','am','is','be'],
    ]),
    unit("What's amazing about plants?",
      'flower=花|fruit=果实|leaf=叶子|soil=土壤|sunflower=向日葵|seed=种子|plant=植物|grow=生长',[
      ['Plants {need} water.','needs','needing','are need'],
      ['A sunflower {has} a long stem.','have','having','are'],
      ['{Do} plants need sunlight? Yes, they do.','Does','Is','Are'],
      ['Let us {plant} some seeds.','plants','planting','to plant'],
    ]),
    unit('How do we keep safe on the road?',
      'road=道路|safe=安全的|light=灯|wait=等待|cross=穿过|rule=规则|stop=停下|look=看',[
      ['We must {stop} at a red light.','stops','stopping','to stop'],
      ['{Do} not run on the road.','Does','Is','Are'],
      ['You must {wait} for the green light.','waits','waiting','to wait'],
      ['Can we {cross} the road now?','crosses','crossing','to cross'],
    ]),
    unit('What do our grandparents do?',
      'walk=散步|exercise=锻炼|garden=花园|cook=做饭|clean=打扫|shopping=购物|grandparent=祖父或祖母；外祖父或外祖母|help=帮助',[
      ['My grandmother {cooks} dinner every day.','cook','cooking','is cook'],
      ['What {does} your grandfather do in the morning?','do','is','are'],
      ['They {do} exercise every morning.','does','doing','are do'],
      ['We can {help} our grandparents.','helps','helping','to help'],
    ]),
  ]},
  {id:'4B',grade:4,title:'四年级下册',units:[
    unit('What is your daily schedule?',
      'breakfast=早餐|lunch=午餐|dinner=晚餐|morning=早晨|afternoon=下午|evening=傍晚|usually=通常|schedule=日程安排|brush=刷',[
      ['I {get} up at seven every day.','gets','getting','am get'],
      ['What time {does} she go to school?','do','is','are'],
      ['He {has} breakfast at half past seven.','have','having','is'],
      ['She does not {go} to bed at six.','goes','going','to go'],
    ]),
    unit('What do we like about school?',
      'Chinese=语文|Maths=数学|English=英语|Science=科学|Art=美术|Music=音乐|subject=学科|lesson=课',[
      ['What subjects {do} you like?','does','is','are'],
      ['She {likes} Science.','like','liking','is like'],
      ['We {have} English on Monday.','has','having','are'],
      ['{Does} he like Maths? Yes, he does.','Do','Is','Are'],
    ]),
    unit("What's great about jobs?",
      'job=工作|dentist=牙医|doctor=医生|nurse=护士|teacher=老师|cook=厨师|teeth=牙齿|work=工作',[
      ['What {does} your mother do?','do','is','are'],
      ['She {is} a dentist.','am','are','be'],
      ['A dentist {looks} after our teeth.','look','looking','is look'],
      ['Doctors can {help} sick people.','helps','helping','to help'],
    ]),
    unit('How can we make music?',
      'piano=钢琴|violin=小提琴|guitar=吉他|drum=鼓|flute=长笛|erhu=二胡|pipa=琵琶|triangle=三角铁|concert=音乐会',[
      ['I can {play} the piano.','plays','playing','to play'],
      ['She {is} playing the violin now.','am','are','be'],
      ['They are {making} musical instruments now.','make','makes','to make'],
      ['{Can} you play the guitar? Yes, I can.','Does','Is','Are'],
    ]),
    unit('How do we make art?',
      'square=正方形|rectangle=长方形|triangle=三角形|circle=圆形|shape=形状|side=边|corner=角|paper=纸|picture=图画',[
      ['A square {has} four sides.','have','having','are'],
      ['A circle does not {have} corners.','has','having','to have'],
      ['We can {make} art with leaves.','makes','making','to make'],
      ['How many sides {does} a triangle have?','do','is','are'],
    ]),
    unit('How do we measure time?',
      'hour=小时|minute=分钟|second=秒|day=一天|night=夜晚|month=月|year=年|time=时间|clock=钟',[
      ['What time {is} it?','am','are','be'],
      ['One hour {has} sixty minutes.','have','having','are'],
      ['What {are} they doing now?','am','is','be'],
      ['He is {reading} a book now.','read','reads','to read'],
    ]),
    unit('How do things change?',
      'liquid=液体|solid=固体|gas=气体|melt=融化|freeze=冻结|sugar=糖|salt=盐|cream=奶油|mix=混合|change=变化',[
      ['Let us {mix} the sugar and cream.','mixes','mixing','to mix'],
      ['Shall we {make} an ice drink?','makes','making','to make'],
      ['The ice is {melting} now.','melt','melts','to melt'],
      ['I {am} putting salt in the bag now.','is','are','be'],
    ]),
    unit('How do people get along with each other?',
      'share=分享|help=帮助|kind=友善的|together=一起|honey=蜂蜜|listen=听|sorry=抱歉的|please=请',[
      ['We should {help} each other.','helps','helping','to help'],
      ['Let us {share} the honey.','shares','sharing','to share'],
      ['{Do} not shout at your friends.','Does','Is','Are'],
      ['She {is} kind to her friends.','am','are','be'],
    ]),
  ]},
];
